services:
  iombian-config-file-handler:
    image: ghcr.io/tknika/iombian-config-file-handler:0.2.0
    container_name: iombian-config-file-handler
    restart: unless-stopped
    volumes:
      - /boot/config/parameters.yml:/app/parameters.yml
    networks:
      - iombian-internal-services 
    ports:
      - ${CONFIG_PORT:-5555}:5555
    environment:
      RESET_EVENT: ${RESET_EVENT:-long_long_click}
      BUTTON_EVENTS_HOST: iombian-button-handler
      BUTTON_EVENTS_PORT: ${BUTTON_EVENTS_PORT:-5556}
      SHUTDOWN_SERVICE_HOST: iombian-shutdown-service
      SHUTDOWN_SERVICE_PORT: ${SHUTDOWN_SERVICE_PORT:-5558}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    labels:
      com.iombian-config-file-handler.service.name: "IoMBian Config File Handler"
      com.iombian-config-file-handler.service.author: "Aitor Castaño"
      com.iombian-config-file-handler.service.version: "0.1.0" 
      com.iombian-config-file-handler.service.description: "Configuration file handler. Receives commands for configuration and also handles rebooting the device through an event."
      com.iombian-config-file-handler.service.changelog: "First release."
      com.iombian-config-file-handler.service.documentation_url: ""

      com.iombian-config-file-handler.env.CONFIG_PORT.name: "Configuration port"
      com.iombian-config-file-handler.env.CONFIG_PORT.description: "Port though which other services will access the configuration."
      com.iombian-config-file-handler.env.CONFIG_PORT.type: "integer:1024;65535"
      com.iombian-config-file-handler.env.CONFIG_PORT.default: "5555"

      com.iombian-config-file-handler.env.RESET_EVENT.name: "Reset event"
      com.iombian-config-file-handler.env.RESET_EVENT.description: "Button event that will trigger the device to reset."
      com.iombian-config-file-handler.env.RESET_EVENT.type: "string"
      com.iombian-config-file-handler.env.RESET_EVENT.default: "long_long_click"

      com.iombian-config-file-handler.env.BUTTON_EVENTS_PORT.name: "Button events port"
      com.iombian-config-file-handler.env.BUTTON_EVENTS_PORT.description: "The port where the button events will be published."
      com.iombian-config-file-handler.env.BUTTON_EVENTS_PORT.type: "integer:1024;65535"
      com.iombian-config-file-handler.env.BUTTON_EVENTS_PORT.default: "5556"

      com.iombian-config-file-handler.env.SHUTDOWN_SERVICE_PORT.name: "Shutdown service port"
      com.iombian-config-file-handler.env.SHUTDOWN_SERVICE_PORT.description: "The port where the shutdown commands will be sent."
      com.iombian-config-file-handler.env.SHUTDOWN_SERVICE_PORT.type: "integer:1024;65535"
      com.iombian-config-file-handler.env.SHUTDOWN_SERVICE_PORT.default: "5558"

      com.iombian-config-file-handler.env.LOG_LEVEL.name: "Log level"
      com.iombian-config-file-handler.env.LOG_LEVEL.description: "Log level of the application (INFO, DEBUG, ...)."
      com.iombian-config-file-handler.env.LOG_LEVEL.type: "enum:DEBUG,INFO,WARN,ERROR"
      com.iombian-config-file-handler.env.LOG_LEVEL.default: "INFO"

networks:
  iombian-internal-services:
    external: true
