name: Validate docker-compose.yaml files

on:
  pull_request:

jobs:
  validate-compose-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Checkout marketplace scripts
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MARKETPLACE_SCRIPTS_REPO }}
          path: scripts
          token: ${{ secrets.MARKETPLACE_SCRIPTS_REPO_TOKEN }} # Add only if MARKETPLACE_SCRIPTS_REPO is private
      - name: Track changes
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          base_sha: main
          files: |
            **/docker-compose.yml
            **/docker-compose.yaml
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r scripts/requirements.txt
      - name: Run compose validation
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            python scripts/validate_compose.py $file # Name of the compose validation entry point file
          done

